### ISSUE TITLE
Move one project to the root of the repository

### ISSUE THREAD

**Issue by Spindel** [kevin-civic/civic_news#3]
The repo' (cookiecutter) files belong in the root of the project,  and are currently one level too deep.

It's a simple operation to use `git mv` to place them in the right place.

**Comment by Spindel** [comment]
Tag this as part of the new milestone

**Comment by kevin-civic** [comment]
Is this the preferred way? I've been using 2 Scoops of Django and I thought they suggested the current format

**Comment by Spindel** [comment]
Since the cookiecutter You're using is creating .travis files and others, _that_ one is assuming that it'll be the root of the repository.

**Comment by Spindel** [comment]
The basic method of low friction is "work the way your tools suggest you to work".

**Comment by kevin-civic** [comment]
OK I understand. Any reason on why this practice varies?

<img width="1273" alt="screen shot 2017-12-14 at 10 45 50 am" src="https://user-images.githubusercontent.com/31577650/34003989-60109e92-e0bc-11e7-969b-15ef2be433c6.png">

**Comment by Spindel** [comment]
The TIP there says just that which I suggested, and configuration_root is then separate.
